### ISSUE TITLE
Nome da UFMG na Ficha Catalográfica gerada no exemplo ramon_fev_2022 está em inglês

### ISSUE THREAD

**Issue by dehuachen** [discentesppgcc/template-latex#7]
Link para o exemplo: https://github.com/discentesppgcc/template-latex/blob/main/ppgccufmg-exemplos/ramon_fev_2022/exemplo.pdf

Na ficha catalográfica, o nome da universidade está em inglês. Deveria ser "Universidade Federal de Minas Gerais" mas está como "Federal University of Minas Gerais".

**Sugestão de correção:**

1. remove a linha 177 `\fcuniversity{\ppgcc@university}`
2. adiciona a linha:
`\fcuniversity{\@ifundefined{@portugueseuniversity}{\ppgcc@university}{\@portugueseuniversity}}`
após o trecho:

```
\newcommand*{\portuguesecourse}[1]                         % Nome do curso em port.
  {\gdef\@portuguesecourse{#1}}
```

**Comment by ramongonze** [comment]
Após conversas com a biblioteca central e com o colegiado do PPGCC, chegamos à conclusão de que a ficha catalográfica será fornecida pela biblioteca. Sendo assim, todas as informações para preenchimento da ficha catalográfica será substituída pela adição de um pdf, o que já acontece com a folha de aprovação.
